# Generated by Django 2.0.6 on 2018-06-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Photo'), ('2', 'Article'), ('3', 'Mixed')], default='0', max_length=1, verbose_name='Place type'),
        ),
    ]
