# Generated by Django 2.0.6 on 2018-06-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('2', 'Article'), ('1', 'Photo')], default='2', max_length=1, verbose_name='Type'),
        ),
    ]
