# Generated by Django 2.0.6 on 2018-06-29 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
        ('articles', '0003_auto_20180627_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(blank=True, to='photo.Image', verbose_name='Images'),
        ),
        migrations.AddField(
            model_name='article',
            name='main_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_image', to='photo.Image'),
        ),
    ]
