# Generated by Django 2.0.6 on 2018-06-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('original', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Image')),
                ('thumbnail', models.ImageField(blank=True, default='', upload_to='images/thumbnails/%Y/%m/%d/', verbose_name='Thumbnail')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Order number')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
