# Generated by Django 2.0.6 on 2018-06-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail2x',
            field=models.ImageField(blank=True, default='', upload_to='images/thumbnails/@2x/%Y/%m/%d/', verbose_name='Thumbnail'),
        ),
    ]
