# Generated by Django 2.0.6 on 2018-06-29 08:52

from django.db import migrations, models
import photo.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20180629_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.ImageField(upload_to=photo.models.PathAndRename('images', 'o'), verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', upload_to=photo.models.PathAndRename('images', 't'), verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail2x',
            field=models.ImageField(blank=True, default='', upload_to=photo.models.PathAndRename('images', 't@2x'), verbose_name='Thumbnail @2x'),
        ),
    ]
